### ISSUE TITLE
Could not update user with a new lastSeenAt timestamp

### ISSUE THREAD

**Issue by sceee** [DanWilkerson/sails-google-cloud-datastore#2]
Hi,

Thanks for providing this.
I noticed an error that appears when using this adapter with sails 1.0:
```
error: Background task failed: Could not update user (`5629499534213120`) with a new `lastSeenAt` timestamp.  Error details: AdapterError: Unexpected error from database adapter: Cannot read property 'fetch' of undefined
    at fn (........\api\hooks\custom\index.js:184:20)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```

The code that's been executed in the hooks\custom\index.js is:
```
            var MS_TO_BUFFER = 60*1000;
            var now = Date.now();
            if (loggedInUser.lastSeenAt < now - MS_TO_BUFFER) {
              User.update({id: loggedInUser.id})
              .set({ lastSeenAt: now })
              .exec((err)=>{
                if (err) {
                  sails.log.error('Background task failed: Could not update user (`'+loggedInUser.id+'`) with a new `lastSeenAt` timestamp.  Error details: '+err.stack);
                  return;
                }//•
                sails.log.verbose('Updated the `lastSeenAt` timestamp for user `'+loggedInUser.id+'`.');
                // Nothing else to do here.
              });//_∏_  (Meanwhile...)
            }//ﬁ
```

Additionally, I receive a similar error when I try to create a new data entry for my model via
```
MyEntity.create({
      name: 'Test'
    })
```

It fails in this location:
```
  raw:
   TypeError: Cannot read property 'fetch' of undefined
       at ds.save.then (........\node_modules\sails-google-cloud-datastore\lib\index.js:96:26)
       at <anonymous> }
```
which is this line:
```
        ds.save(entities.map(createSavableEntity))
          .then(() => {

            // HERE COMES THE ERROR
            if (!s3q.meta.fetch) { return done(); }

            const items = entities.map(entity => entityToItem({entity, model}));

            done(null, items);

          }).catch(done);
```

**Comment by DanWilkerson** [comment]
Ah, okay; looks like meta is sometimes not defined at all. Easy fix!

```
if (!s3q.meta || !s3q.meta.fetch) { return done(); }
```

Putting in a patch now...

**Comment by sceee** [comment]
Great, thanks!

**Comment by DanWilkerson** [comment]
Should be all set, LMK!
