### ISSUE TITLE
Error in create function: cannot read property '0' of undefined

### ISSUE THREAD

**Issue by sceee** [DanWilkerson/sails-google-cloud-datastore#3]
I am getting the following error when trying to save a model entry:
```
TypeError: Cannot read property '0' of undefined
       at createEach (...\node_modules\sails-google-cloud-datastore\lib\index.js:124:23)
       at ds.save.then (...\node_modules\sails-google-cloud-datastore\lib\index.js:96:56)
```

The particular code in this location is:
```
  create: function (identity, s3q, done) {

    s3q.newRecords = [s3q.newRecord];

    this.createEach(identity, s3q, (err, items) => {

      if (err) { return done(err); }

      done(null, items[0]); // <--- this is where the error comes

    });

  },
```

**Comment by DanWilkerson** [comment]
Should be fixed, thanks :)

**Comment by sceee** [comment]
Great, thanks!
